version: "3"
services:
    client:
        build:
            context: ./client
            target: base
        image: front:FA-SR
        stdin_open: true
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules
        command: tail -f /dev/null
        networks:
            - FA-SR
    server:
        build:
            context: ./server
            target: base
        image: back:FA-SR
        ports:
            - "5000:5000"
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
        command: tail -f /dev/null
        networks:
            - FA-SR
networks:
    FA-SR:
        driver: bridge
