version: "3"
services:
    client:
        build: ./client
        image: front:FA-SR
        stdin_open: true
        ports:
            - "80:80"
        networks:
            - FA-SR
    server:
        build: ./server
        image: back:FA-SR
        ports:
            - "5000:5000"
        networks:
            - FA-SR
networks:
    FA-SR:
        driver: bridge
