version: "3"
services:
    client:
        build: ./client
        image: front:FA-SR
        stdin_open: true
        ports:
            - "3000:3000"
        networks:
            - FA-SR
    server:
        build: ./server
        image: back:FA-SR
        ports:
            - "5000:5000"
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - FA-SR
networks:
    FA-SR:
        driver: bridge
